version: 2.1

orbs:
  octopus-cli: octopusdeploylabs/octopus-cli@0.0.3
  docker: circleci/docker@2.4.0

jobs:
  build-and-push:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Set version tag
          command: echo "0.4.${CIRCLE_BUILD_NUM}" > version.txt

      - run:
          name: Build project JAR
          command: mvn -B package --file pom.xml

      - run:
          name: Build Docker image
          command: |
            VERSION_TAG=$(cat version.txt)
            docker build -t $ACR_NAME.azurecr.io/$IMAGE_NAME:$VERSION_TAG .

      - run:
          name: Login to ACR
          command: |
            echo $ACR_PASSWORD | docker login $ACR_NAME.azurecr.io -u $ACR_USERNAME --password-stdin

      - run:
          name: Push Docker image to ACR
          command: |
            VERSION_TAG=$(cat version.txt)
            docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:$VERSION_TAG

      - octopus-cli/install  # <-- This installs the CLI tool via orb

      - run:
          name: Create Octopus Release
          command: |
            VERSION_TAG=$(cat version.txt)
            octo create-release \
              --server $OCTOPUS_SERVER_URL \
              --apiKey $OCTOPUS_API_KEY \
              --project "$OCTOPUS_PROJECT" \
              --releaseNumber "$VERSION_TAG" \
              --package "$OCTOPUS_PACKAGE_NAME:$VERSION_TAG"
