version: 2.1

orbs:
  docker: circleci/docker@2.4.0

jobs:
  build-and-release:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout

      - run:
          name: Set Version Tag (YYYY.MM.BUILDNUM)
          command: |
            VERSION="$(date +'%Y.%m').${CIRCLE_BUILD_NUM}"
            echo $VERSION > version.txt
            echo "Version set to $VERSION"

      - run:
          name: Build Java Project
          command: mvn -B package --file pom.xml

      - setup_remote_docker

      - run:
          name: Build Docker Image
          command: |
            VERSION=$(cat version.txt)
            docker build -t $ACR_NAME.azurecr.io/$IMAGE_NAME:$VERSION .

      - run:
          name: Login to Azure Container Registry
          command: |
            echo $ACR_PASSWORD | docker login $ACR_NAME.azurecr.io -u $ACR_USERNAME --password-stdin

      - run:
          name: Push Docker Image to ACR
          command: |
            VERSION=$(cat version.txt)
            docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:$VERSION

      - run:
          name: Install Octopus CLI
          command: |
            OCTO_VERSION="9.1.7"
            OCTO_FILENAME="OctopusTools.${OCTO_VERSION}.linux-x64.tar.gz"
            OCTO_URL="https://github.com/OctopusDeploy/OctopusCLI/releases/download/v${OCTO_VERSION}/${OCTO_FILENAME}"

            curl -L -f -o $OCTO_FILENAME $OCTO_URL
            tar -xzf $OCTO_FILENAME
            chmod +x octo
            sudo mv octo /usr/local/bin/octo

      - run:
          name: Create Octopus Release Only
          command: |
            VERSION=$(cat version.txt)
            octo create-release \
              --project "$OCTO_PROJECT" \
              --releaseNumber "$VERSION" \
              --package "Azure - Deploy Container App:$VERSION" \
              --server "$OCTO_SERVER_URL" \
              --apiKey "$OCTO_API_KEY"

workflows:
  version: 2
  build-and-release:
    jobs:
      - build-and-release
