version: 2.1

orbs:
  docker: circleci/docker@2.4.0

jobs:
  build-and-push:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Set version tag
          command: |
            echo "0.4.${CIRCLE_BUILD_NUM}" > version.txt
      - run:
          name: Build project JAR
          command: mvn -B package --file pom.xml
      - run:
          name: Build Docker image
          command: |
            VERSION_TAG=$(cat version.txt)
            docker build -t $ACR_NAME.azurecr.io/$IMAGE_NAME:$VERSION_TAG .
      - run:
          name: Login to ACR
          command: |
            echo $ACR_PASSWORD | docker login $ACR_NAME.azurecr.io -u $ACR_USERNAME --password-stdin
      - run:
          name: Push image to ACR
          command: |
            VERSION_TAG=$(cat version.txt)
            docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:$VERSION_TAG
      - persist_to_workspace:
          root: .
          paths:
            - version.txt

  trigger-octopus:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Read version
          command: |
            export VERSION_TAG=$(cat version.txt)
            echo "export VERSION_TAG=$VERSION_TAG" >> $BASH_ENV
      - run:
          name: Install Octopus CLI
          command: |
            curl -LO https://download.octopusdeploy.com/octopus-tools/OctopusTools.8.2.4748.linux-x64.tar.gz
            mkdir octo-cli
            tar -xzvf OctopusTools.8.2.4748.linux-x64.tar.gz -C octo-cli
            chmod +x octo-cli/octo
      - run:
          name: Trigger Octopus CLI Release
          command: |
            source $BASH_ENV
            ./octo-cli/octo create-release \
              --project "Test Azure Container App Deployment" \
              --releaseNumber "$VERSION_TAG" \
              --packageVersion "$VERSION_TAG" \
              --server "$OCTOPUS_URL" \
              --apiKey "$OCTOPUS_API_KEY"

workflows:
  build-deploy:
    jobs:
      - build-and-push
      - trigger-octopus:
          requires:
            - build-and-push
