version: 2.1

orbs:
  docker: circleci/docker@2.4.0

jobs:
  build-and-deploy:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout

      - run:
          name: Set Version
          command: echo "0.1.${CIRCLE_BUILD_NUM}" > version.txt

      - run:
          name: Build JAR
          command: mvn -B package --file pom.xml

      - setup_remote_docker

      - run:
          name: Build Docker Image
          command: |
            VERSION=$(cat version.txt)
            docker build -t $ACR_NAME.azurecr.io/$IMAGE_NAME:$VERSION .

      - run:
          name: Login to Azure Container Registry
          command: |
            echo $ACR_PASSWORD | docker login $ACR_NAME.azurecr.io -u $ACR_USERNAME --password-stdin

      - run:
          name: Push Docker Image to ACR
          command: |
            VERSION=$(cat version.txt)
            docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:$VERSION

- run:
    name: Install Octopus CLI
    command: |
      OCTO_VERSION="9.1.6"
      curl -sSL https://github.com/OctopusDeploy/OctopusCLI/releases/download/v${OCTO_VERSION}/OctopusCLI.${OCTO_VERSION}.linux-x64.tar.gz -o octo.tar.gz
      tar -xzf octo.tar.gz
      chmod +x octo
      sudo mv octo /usr/local/bin/octo

      - run:
          name: Create Octopus Release
          command: |
            VERSION=$(cat version.txt)
            octo create-release \
              --project "$OCTO_PROJECT" \
              --releaseNumber "$VERSION" \
              --package "$OCTO_PACKAGE_NAME:$VERSION" \
              --server "$OCTO_SERVER_URL" \
              --apiKey "$OCTO_API_KEY"

      - run:
          name: Deploy Release to Environment
          command: |
            VERSION=$(cat version.txt)
            octo deploy-release \
              --project "$OCTO_PROJECT" \
              --releaseNumber "$VERSION" \
              --deployTo "$OCTO_ENVIRONMENT" \
              --server "$OCTO_SERVER_URL" \
              --apiKey "$OCTO_API_KEY"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-and-deploy
