jobs:
  build-and-push:
    machine: true  # enables Docker daemon
    environment:
      IMAGE_NAME: springboot-acr-test
    steps:
      - checkout

      - run:
          name: Set version tag
          command: |
            VERSION_TAG="0.4.$(git rev-list --count HEAD)"
            echo "export VERSION_TAG=$VERSION_TAG" >> $BASH_ENV
            echo "Version Tag: $VERSION_TAG"

      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:$VERSION_TAG .

      - run:
          name: Authenticate with Azure Container Registry
          command: |
            echo "$ACR_PASSWORD" | docker login $ACR_LOGIN_SERVER -u $ACR_USERNAME --password-stdin

      - run:
          name: Push image to ACR
          command: |
            docker tag $IMAGE_NAME:$VERSION_TAG $ACR_LOGIN_SERVER/$IMAGE_NAME:$VERSION_TAG
            docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:$VERSION_TAG

      - run:
          name: Trigger Octopus Release
          command: |
            curl -X POST "$OCTOPUS_URL/api/releases" \
              -H "X-Octopus-ApiKey: $OCTOPUS_API_KEY" \
              -H "Content-Type: application/json" \
              -d "{
                \"ProjectId\": \"$OCTOPUS_PROJECT_ID\",
                \"Version\": \"$VERSION_TAG\",
                \"SelectedPackages\": [
                  {
                    \"StepName\": \"Azure - Deploy Container App\",
                    \"Version\": \"$VERSION_TAG\"
                  }
                ]
              }"
